// <auto-generated />
using System;
using Infrastructure.Repositories.Sql.Automoviles;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Repositories.Sql.Automoviles.Migrations
{
    [DbContext(typeof(AutomovilesDbContext))]
    [Migration("20251001173608_Sync_Snapshot_Remove_Tipo")]
    partial class Sync_Snapshot_Remove_Tipo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Automovil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NumeroMotor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroMotor")
                        .IsUnique()
                        .HasDatabaseName("IX_Automovil_NumeroMotor");

                    b.ToTable("Automovil", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Automovil", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Vin", "NumeroChasis", b1 =>
                        {
                            b1.Property<int>("AutomovilId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(17)
                                .HasColumnType("nvarchar(17)")
                                .HasColumnName("NumeroChasis");

                            b1.HasKey("AutomovilId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("IX_Automovil_NumeroChasis")
                                .HasFilter("[NumeroChasis] IS NOT NULL");

                            b1.ToTable("Automovil");

                            b1.WithOwner()
                                .HasForeignKey("AutomovilId");
                        });

                    b.Navigation("NumeroChasis")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
