<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Legacy\**\*.cs" />
    <EmbeddedResource Remove="Legacy\**\*" />
    <None Remove="Legacy\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DomainServices\" />
    <Folder Include="Aggregators\" />
    <Folder Include="Contracts\" />
    <Folder Include="ValueObjects\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Legacy\README.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Domain\Core.Domain.csproj" />
  </ItemGroup>

</Project>
